---
# Inventario Ansible — Rocky Linux AIOps Lab
# Ejecución local dentro de la VM
# Cuando se ejecute desde la Mac, cambiar a conexión SSH con los parámetros comentados

all:
    hosts:
        rocky-aiops:
            ansible_host: localhost
            ansible_connection: local
            ansible_python_interpreter: /usr/bin/python3
            ansible_become: true
